### ISSUE TITLE
not really an issue, but-

### ISSUE THREAD

**Issue by vfxbroseph** [ElbowBaggins/GinsorAudioTool2Plus#1]
In this github readme, there seems to be about 30% useful information and 70% hostility towards this Ginsor guy. Is it really necessary? I find myself not wanting to read the whole thing because it just sounds like a personal vendetta. Its a shame because i feel that the technical side is interesting, but i just cant help but feel a wave of hate hitting me while reading. I hope you can change this sometime because it is honestly a good rework of the tool

**Comment by ElbowBaggins** [comment]
There's a true rewrite in Rust in the tubes which is more capable and has more technical details, probably more interesting than anything in the readme tbh, as it IS mostly a personal vendetta.

The tone is as such because I _tried_ to help civilly and fix the tool's issues back in the V1 days and was rebuffed. He also does things like releasing content from the game (such as models) while refusing to make tools or even specs available. I'm militaristically in favor of information freedom so I find that kind of behavior repugnant and successfully did my best to end it. 

I will probably still tone down the main readme sometime soon (perhaps moving the rest of it to RANT. MD) as you are not the only one with this view. I think I've delivered enough smugness by now. I've actually received a PR to update this for BL, which is exactly the sort of community response I wished that Ginsor would have accepted, so I suppose the time for my outrage has passed.
