### ISSUE TITLE
Tool takes an unreasonably long time to load anything

### ISSUE THREAD

**Issue by RumekFuria** [ElbowBaggins/GinsorAudioTool2Plus#5]
title
for me the tool is stuck at the "Generating PKG Database. Please wait..." step
I can see CPU usage from it in the task manager, so it's doing something, but I'm not seeing usage of anything else
left it running for... I dunno, 20 minutes? more? and it still hasn't loaded anything
I made sure that antivirus isn't blocking it, and ran it with admin perms
any ideas?

**Comment by RumekFuria** [comment]
update
to make sure it isn't just taking it's time, I left it to run for much longer. still nothing
I also moved it to the same disc as the game is just in case
![image](https://user-images.githubusercontent.com/3901751/105159430-5c883700-5b0f-11eb-9616-037addd26cbc.png)

**Comment by ElbowBaggins** [comment]
Okay, so, first off, if you build from source (from `master`) it will work because this was fixed by Pull Request #3.

The current "release" here does not have this fix yet (what with it being from June and all) and this results in the behavior you're seeing.

If you're interested in the mechanism at play here, basically, Ginsor's "PKG Database" is more of a subset of what a "proper" PKG Database would contain. It essentially boils down to a giant map of "file" IDs to "text" IDs (i.e. X voice clip maps to Y text, usually the subtitle content). In Beyond Light, the IDs used to identify certain contents in the PKG files changed. As such, the ID used to identify text content and "voice lines" does not match, no "voice lines" are found, the database remains empty and the app believes it is never done loading.

This ID change likely corresponds with changes to Bungie's internal build pipeline and is actually the first such change since, I believe, Destiny 1.

I'm going to try to get the CI build set up so you can get the latest build without building it yourself.

**Comment by RumekFuria** [comment]
Understandable
figured it might be connected to BL in some way

**Comment by ElbowBaggins** [comment]
I uploaded a new build with the issue resolved. You may or may not have to install the .NET 5 runtime as I have migrated the project over (which brings some mild perf improvements in general).
